#' A synthetic consumer loan portfolio
#'
#' Two thousand personal loans over four origination years, with the outcome,
#' the predictors a lender would model on, and one attribute a lender is not
#' allowed to model on. Generated rather than collected, because the public
#' credit panels that can be redistributed have had exactly that last column
#' removed, and the fairness question this dataset exists for cannot be asked
#' without it.
#'
#' @format A data frame with 2,000 rows and 13 columns:
#' \describe{
#'   \item{default}{Did the loan default? A factor, `"no"` or `"yes"`. 16.4
#'     per cent `"yes"`, rising from 13.8 per cent in the 2019 vintage to 19.9
#'     per cent in 2022.}
#'   \item{amount}{Amount borrowed, in whole units of 25.}
#'   \item{income}{Annual income as stated at application.}
#'   \item{dti}{Debt-to-income ratio at origination.}
#'   \item{term}{Repayment term, `"36 months"` or `"60 months"`.}
#'   \item{employment}{Years in the current job, censored at 40.}
#'   \item{score}{Credit score at application, 300 to 850.}
#'   \item{utilisation}{Revolving credit utilisation, 0 to 1.}
#'   \item{delinquencies}{Delinquencies in the previous two years.}
#'   \item{home}{Housing status: `"rent"`, `"mortgage"` or `"own"`.}
#'   \item{purpose}{Stated purpose of the loan, five levels.}
#'   \item{vintage}{Origination year, 2019 to 2022.}
#'   \item{applicant_group}{A protected attribute, `"A"` or `"B"`. It enters
#'     the default probability nowhere: given the predictors it carries no
#'     information about the outcome at all.}
#' }
#'
#' @section What was built into it, and why:
#' A synthetic portfolio is only worth shipping if the questions asked of it
#' have answers that are in the data rather than in the telling. Three things
#' were put there on purpose.
#'
#' Default depends on the score, the utilisation and the debt-to-income ratio,
#' and on an interaction between a thin score and a high utilisation, so the
#' proximity has blocks in it rather than one gradient.
#'
#' The utilisation carries three times the weight in the 2022 vintage that it
#' carries in 2019. Whether the forest reorganises its view of the portfolio
#' between origination years is then a question about the data and not about
#' sampling noise.
#'
#' `applicant_group` shifts the median income by 8,902 and the median score by
#' 29 points, and affects the default probability not at all. A forest fitted
#' without it will still separate the groups, because the predictors carry
#' them. How much of the proximity that accounts for is what
#' [permanova()] measures, and it is a fairness diagnostic that does not
#' require the model to have used the attribute.
#'
#' @source Generated by `inst/data-raw/loans.R`, which is shipped with the
#'   package and records the specification above as code. Re-runnable, seeded,
#'   and not a stand-in for a real portfolio: the numbers are realistic in
#'   shape and invented in fact.
#' @seealso `vignette("credit-scoring-case")`, which is the case study this
#'   data was generated for.
#' @examples
#' summary(loans$default)
#' round(tapply(loans$default == "yes", loans$vintage, mean), 3)
"loans"
